### ISSUE TITLE
Problems with using a function called ‘’waveform.percentile‘’ 

### ISSUE THREAD

**Issue by tudoulei** [SmithB/IS2_calval#1]
![image](https://user-images.githubusercontent.com/34886368/53475089-08eb4b00-3aaa-11e9-9faf-019cd3415d13.png)

**Comment by tudoulei** [comment]
els is None ,but this problem still exists.

**Comment by SmithB** [comment]
Can you give an example that shows the waveform that produced this problem?

**Comment by tudoulei** [comment]
[mabel.zip](https://github.com/SmithB/IS2_calval/files/2912917/mabel.zip)

**Comment by SmithB** [comment]
Thanks for pointing that out.  I think the latest commit fixed your problem: the interp function only take a 1-d abscissa, and in your example, wave1.t was Nx1.  I added a ravel() statement to the interp call, and it seems to have fixed the problem.
